### PR TITLE
Add fields comparator to config of form make functor

### LINKED ISSUE #52: FormId compare is not save
hi @alexfedoseev 

I've noticed that Formality__Form.re uses `Pervasives.compare`:
```reason
module Make = (Form: Form) => {
  module FieldId =
    Id.MakeComparable({
      type t = Form.field;
      let cmp = Pervasives.compare;
    });
  ...
}
```

it will throw error in runtime if Form.field is complex type that has function or any other non-comparable type)

Maybe it should be something like this:
```reason
module type Form = {
  type field;
  type state;
  type message;
  type submissionError;
  let validators: list(Validation.validator(field, state, message));
  module FieldId:
    { type identity; type t = field; let cmp: Id.cmp(t, identity); };
};

module Make = (Form: Form) => {
  module FieldId = Form.FieldId;
  ...
}

```

### PR DESCRIPTION
**Pull request by Coobaha**
Adds helper functors to provide custom fields comparator to form config

resolves #52

### CODE REVIEW

**Comment by Coobaha** [comment]
One thing i am not happy with this approach about is js output, it is inlined per functor.

**Comment by Coobaha** [comment]
Seems that bucklescript doesn't inline modules when they are coming from the other file

**Comment by Coobaha** [comment]
I moved make functors to new files, this eliminates duplicated output (and adds a lot of diff :D)
I made potential internal breaking changes (module aliases were moved in files prefixed with __). Maybe worth to add to the changelog

**Comment by Coobaha** [comment]
@alexfedoseev ping! :)

**Comment by Coobaha** [comment]
@alexfedoseev no worries, renaming done :)

**Comment by alexfedoseev** [comment]
@Coobaha Renaming looks good! And the second point?

**Comment by Coobaha** [comment]
ah, sorry i've missed it. My initial version was using functors in the same file. Problem is that it doubles the size of javascript output, Bucklescript inlines same code to `Make` and to `MakeWithId`

**Comment by alexfedoseev** [comment]
Oh, good catch! Then LGTM. Thanks again!

**Pull request merged**
